import { notFound,redirect } from "next/navigation";
import { createSessionClient } from "@/lib/supabase/server";
import { CommerceShell } from "@/components/commerce/shell";
import { PrintInvoice } from "@/components/commerce/print-invoice";
import { formatMoney,uuidPattern } from "@/lib/commerce/validation";
import type { Currency } from "@/lib/commerce/types";
export const metadata={title:"Invoice",robots:{index:false,follow:false}};
type Invoice={invoice_number:number;billing_name:string;billing_email:string;organization:string|null;currency:Currency;subtotal:number;discount_total:number;total:number;items_snapshot:Array<{title:string;type:string;quantity:number;unit_amount:number}>;issued_at:string;orders:{order_number:number};credit_notes:Array<{credit_number:number;amount:number;reason:string;issued_at:string}>};
export default async function InvoicePage({params}:{params:Promise<{id:string}>}){const {id}=await params;if(!uuidPattern.test(id))notFound();const db=await createSessionClient();const {data:{user}}=await db.auth.getUser();if(!user?.email_confirmed_at)redirect(`/auth?next=/account/orders/${id}/invoice`);const {data}=await db.from("invoices").select("invoice_number,billing_name,billing_email,organization,currency,subtotal,discount_total,total,items_snapshot,issued_at,orders!inner(order_number),credit_notes(credit_number,amount,reason,issued_at)").eq("order_id",id).maybeSingle();if(!data)notFound();const invoice=data as unknown as Invoice;return <CommerceShell title={`Invoice INV-${invoice.invoice_number}`}><article className="surface-card mx-auto max-w-3xl space-y-6 p-8"><div className="flex justify-between gap-4"><div><strong>UZYNTRA Security</strong><p>Order UZ-{invoice.orders.order_number}</p></div><PrintInvoice/></div><div><p>{invoice.billing_name}</p>{invoice.organization&&<p>{invoice.organization}</p>}<p>{invoice.billing_email}</p><p>Issued {new Date(invoice.issued_at).toLocaleDateString("en-GB",{timeZone:"UTC"})}</p></div><table className="w-full"><thead><tr><th className="text-left">Item</th><th>Qty</th><th className="text-right">Amount</th></tr></thead><tbody>{invoice.items_snapshot.map((item,index)=><tr key={index}><td>{item.title}</td><td className="text-center">{item.quantity}</td><td className="text-right">{formatMoney(item.unit_amount,invoice.currency)}</td></tr>)}</tbody></table>{invoice.discount_total>0&&<p>Discount: −{formatMoney(invoice.discount_total,invoice.currency)}</p>}<p className="text-xl font-bold">Total paid: {formatMoney(invoice.total,invoice.currency)}</p>{invoice.credit_notes?.map(note=><section key={note.credit_number} className="border-t pt-4"><strong>Credit note CN-{note.credit_number}</strong><p>{formatMoney(note.amount,invoice.currency)} · {note.reason}</p></section>)}</article></CommerceShell>}
