-- Initial catalog imported from repository prices on 2026-09-25.
-- Fixed regional prices, not currency conversions. Review before launch.
insert into public.offerings(slug,type,title,active) values ('artificial-intelligence','course','Artificial Intelligence',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',5400000 from public.offerings where slug='artificial-intelligence';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',24900 from public.offerings where slug='artificial-intelligence';
insert into public.offerings(slug,type,title,active) values ('cybersecurity','course','Cyber Security',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',4500000 from public.offerings where slug='cybersecurity';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',19900 from public.offerings where slug='cybersecurity';
insert into public.offerings(slug,type,title,active) values ('cloud-computing','course','Cloud Computing',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',5400000 from public.offerings where slug='cloud-computing';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',24900 from public.offerings where slug='cloud-computing';
insert into public.offerings(slug,type,title,active) values ('devsecops','course','DevOps and DevSecOps',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',5400000 from public.offerings where slug='devsecops';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',24900 from public.offerings where slug='devsecops';
insert into public.offerings(slug,type,title,active) values ('python-programming','course','Python Programming',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',2400000 from public.offerings where slug='python-programming';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',14900 from public.offerings where slug='python-programming';
insert into public.offerings(slug,type,title,active) values ('web-development','course','Web Development',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',4500000 from public.offerings where slug='web-development';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',19900 from public.offerings where slug='web-development';
insert into public.offerings(slug,type,title,active) values ('mobile-app-development','course','Mobile App Development',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',4500000 from public.offerings where slug='mobile-app-development';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',19900 from public.offerings where slug='mobile-app-development';
insert into public.offerings(slug,type,title,active) values ('data-science','course','Data Science and Analytics',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',5400000 from public.offerings where slug='data-science';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',24900 from public.offerings where slug='data-science';
insert into public.offerings(slug,type,title,active) values ('blockchain-web3','course','Blockchain and Web3',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',6000000 from public.offerings where slug='blockchain-web3';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',29900 from public.offerings where slug='blockchain-web3';
insert into public.offerings(slug,type,title,active) values ('automation','course','Automation (n8n)',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',3000000 from public.offerings where slug='automation';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',17900 from public.offerings where slug='automation';
insert into public.offerings(slug,type,title,active) values ('prompt-engineering','course','Prompt Engineering',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',1500000 from public.offerings where slug='prompt-engineering';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',9900 from public.offerings where slug='prompt-engineering';
insert into public.offerings(slug,type,title,active) values ('ai-agent-development','course','AI Agent Development',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',4000000 from public.offerings where slug='ai-agent-development';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',24900 from public.offerings where slug='ai-agent-development';
insert into public.offerings(slug,type,title,active) values ('ethical-hacking','course','Ethical Hacking',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',5400000 from public.offerings where slug='ethical-hacking';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',24900 from public.offerings where slug='ethical-hacking';
insert into public.offerings(slug,type,title,active) values ('penetration-testing','course','Penetration Testing',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',6000000 from public.offerings where slug='penetration-testing';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',29900 from public.offerings where slug='penetration-testing';
insert into public.offerings(slug,type,title,active) values ('api-security','course','API Security',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',4000000 from public.offerings where slug='api-security';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',24900 from public.offerings where slug='api-security';
insert into public.offerings(slug,type,title,active) values ('secure-coding','course','Secure Coding',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',3600000 from public.offerings where slug='secure-coding';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',19900 from public.offerings where slug='secure-coding';
insert into public.offerings(slug,type,title,active) values ('linux-administration','course','Linux Administration',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',2400000 from public.offerings where slug='linux-administration';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',14900 from public.offerings where slug='linux-administration';
insert into public.offerings(slug,type,title,active) values ('docker-kubernetes','course','Docker and Kubernetes',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',3600000 from public.offerings where slug='docker-kubernetes';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',22900 from public.offerings where slug='docker-kubernetes';
insert into public.offerings(slug,type,title,active) values ('aws-azure-gcp','course','AWS / Azure / GCP',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',6000000 from public.offerings where slug='aws-azure-gcp';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',29900 from public.offerings where slug='aws-azure-gcp';
insert into public.offerings(slug,type,title,active) values ('networking-ccna','course','Networking (CCNA)',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',6500000 from public.offerings where slug='networking-ccna';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',19900 from public.offerings where slug='networking-ccna';
insert into public.offerings(slug,type,title,active) values ('soc-analyst','course','SOC Analyst',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',5400000 from public.offerings where slug='soc-analyst';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',24900 from public.offerings where slug='soc-analyst';
insert into public.offerings(slug,type,title,active) values ('digital-forensics','course','Digital Forensics',true);
insert into public.prices(offering_id,currency,region,amount) select id,'PKR','PK',6000000 from public.offerings where slug='digital-forensics';
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',29900 from public.offerings where slug='digital-forensics';

-- The dedicated Offensive AI page only specifies USD 400. Do not invent a PKR price.
insert into public.offerings(slug,type,title,active) values ('offensive-ai','course','Offensive AI: Certified Web Pentester',true);
insert into public.prices(offering_id,currency,region,amount) select id,'USD','international',40000 from public.offerings where slug='offensive-ai';
